export const assets = [
  {
    id: "AST-001",
    name: "Dell Latitude 5520",
    type: "Laptop",
    category: "IT Equipment",
    status: "Active",
    assignedTo: "Priya Sharma",
    department: "Engineering",
    location: "Mumbai Office",
    purchaseDate: "2023-01-15",
    purchaseCost: "₹75,000",
    currentValue: "₹65,000",
    serialNumber: "DL5520-2023-001",
  },
  {
    id: "AST-002",
    name: "HP LaserJet Pro",
    type: "Printer",
    category: "IT Equipment",
    status: "Active",
    assignedTo: "IT Department",
    department: "IT",
    location: "Delhi Office",
    purchaseDate: "2022-08-20",
    purchaseCost: "₹25,000",
    currentValue: "₹18,000",
    serialNumber: "HP-LJ-2022-045",
  },
  {
    id: "AST-003",
    name: "Mahindra XUV500",
    type: "Vehicle",
    category: "Transport",
    status: "Under Maintenance",
    assignedTo: "Transport Pool",
    department: "Operations",
    location: "Bangalore Garage",
    purchaseDate: "2021-05-10",
    purchaseCost: "₹18,50,000",
    currentValue: "₹14,20,000",
    serialNumber: "MH-XUV-2021-789",
  },
  {
    id: "AST-004",
    name: "Conference Table",
    type: "Furniture",
    category: "Office Furniture",
    status: "Active",
    assignedTo: "Meeting Room A",
    department: "Administration",
    location: "Pune Office",
    purchaseDate: "2022-11-05",
    purchaseCost: "₹45,000",
    currentValue: "₹38,000",
    serialNumber: "FUR-CT-2022-156",
  },
  {
    id: "AST-005",
    name: "MacBook Pro 16",
    type: "Laptop",
    category: "IT Equipment",
    status: "Active",
    assignedTo: "Amit Patel",
    department: "Design",
    location: "Hyderabad Office",
    purchaseDate: "2023-03-12",
    purchaseCost: "₹2,15,000",
    currentValue: "₹1,95,000",
    serialNumber: "MBP16-2023-089",
  },
  {
    id: "AST-006",
    name: "Server Rack HP",
    type: "Server",
    category: "IT Infrastructure",
    status: "Active",
    assignedTo: "Data Center",
    department: "IT",
    location: "Chennai Data Center",
    purchaseDate: "2022-01-20",
    purchaseCost: "₹8,50,000",
    currentValue: "₹6,20,000",
    serialNumber: "HP-SR-2022-034",
  },
  {
    id: "AST-007",
    name: "Office Building Wing A",
    type: "Property",
    category: "Real Estate",
    status: "Active",
    assignedTo: "Corporate Office",
    department: "Facilities",
    location: "Gurgaon",
    purchaseDate: "2020-06-15",
    purchaseCost: "₹5,50,00,000",
    currentValue: "₹6,20,00,000",
    serialNumber: "PROP-GGN-2020-001",
  },
  {
    id: "AST-008",
    name: "iPhone 14 Pro",
    type: "Mobile",
    category: "IT Equipment",
    status: "Active",
    assignedTo: "Sneha Reddy",
    department: "Sales",
    location: "Kolkata Office",
    purchaseDate: "2023-09-05",
    purchaseCost: "₹1,29,000",
    currentValue: "₹1,10,000",
    serialNumber: "IP14P-2023-234",
  },
];

export const maintenanceRecords = [
  {
    id: "MNT-001",
    assetId: "AST-003",
    assetName: "Mahindra XUV500",
    type: "Breakdown",
    status: "In Progress",
    reportedBy: "Vikram Singh",
    reportedDate: "2024-01-10",
    scheduledDate: "2024-01-12",
    vendor: "Mahindra Service Center",
    estimatedCost: "₹15,000",
    priority: "High",
  },
  {
    id: "MNT-002",
    assetId: "AST-002",
    assetName: "HP LaserJet Pro",
    type: "Preventive",
    status: "Scheduled",
    reportedBy: "IT Department",
    reportedDate: "2024-01-08",
    scheduledDate: "2024-01-20",
    vendor: "HP Authorized Service",
    estimatedCost: "₹2,500",
    priority: "Low",
  },
  {
    id: "MNT-003",
    assetId: "AST-006",
    assetName: "Server Rack HP",
    type: "Preventive",
    status: "Completed",
    reportedBy: "System Admin",
    reportedDate: "2023-12-15",
    scheduledDate: "2023-12-20",
    completedDate: "2023-12-20",
    vendor: "HP Enterprise Support",
    estimatedCost: "₹25,000",
    actualCost: "₹23,500",
    priority: "Medium",
  },
];

export const procurementRequests = [
  {
    id: "PR-001",
    title: "10 Dell Laptops",
    requestedBy: "Meera Iyer",
    department: "Engineering",
    requestDate: "2024-01-05",
    status: "Pending Approval",
    estimatedCost: "₹7,50,000",
    priority: "High",
    vendor: "Dell India",
  },
  {
    id: "PR-002",
    title: "Office Chairs (25 units)",
    requestedBy: "Admin Team",
    department: "Administration",
    requestDate: "2024-01-08",
    status: "Approved",
    estimatedCost: "₹2,50,000",
    priority: "Medium",
    vendor: "Featherlite",
  },
  {
    id: "PR-003",
    title: "Network Switches",
    requestedBy: "Karthik Rao",
    department: "IT",
    requestDate: "2024-01-10",
    status: "In Procurement",
    estimatedCost: "₹1,20,000",
    priority: "High",
    vendor: "Cisco Systems",
  },
];

export const notifications = [
  {
    id: 1,
    type: "warning",
    title: "Maintenance Due",
    message: "Server Rack HP (AST-006) preventive maintenance due in 3 days",
    time: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "info",
    title: "Approval Required",
    message: "Purchase request PR-001 awaiting your approval",
    time: "5 hours ago",
    read: false,
  },
  {
    id: 3,
    type: "success",
    title: "Asset Added",
    message: "New asset iPhone 14 Pro (AST-008) successfully added",
    time: "1 day ago",
    read: true,
  },
  {
    id: 4,
    type: "warning",
    title: "Warranty Expiring",
    message: "Dell Latitude 5520 (AST-001) warranty expires in 30 days",
    time: "2 days ago",
    read: true,
  },
];

export const cities = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Gurgaon",
  "Noida",
  "Kochi",
];

export const employees = [
  "Priya Sharma",
  "Amit Patel",
  "Sneha Reddy",
  "Vikram Singh",
  "Meera Iyer",
  "Karthik Rao",
  "Anjali Desai",
  "Rahul Verma",
  "Deepika Nair",
  "Arjun Mehta",
];
